on:
  push:
    branches:
      - master

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_a5573c8f_bfbd_447e_8e1d_5bab1d2901e7_API_KEY }}
          config_path_input: 'openfn-a5573c8f-bfbd-447e-8e1d-5bab1d2901e7-config.json'
